/**
 * VELORA AI — Model Capability Registry
 * 
 * Authoritative registry of all models across all modalities and providers.
 * Strictly enforces truth in capabilities: no provider is assigned unsupported modalities.
 */

export type Modality = 'text' | 'image' | 'video' | 'audio';
export type TaskType =
  | 'CHAT'
  | 'REASONING'
  | 'CODING'
  | 'RESEARCH'
  | 'VISION_ANALYSIS'
  | 'TEXT_TO_IMAGE'
  | 'IMAGE_TO_IMAGE'
  | 'TEXT_TO_VIDEO'
  | 'IMAGE_TO_VIDEO'
  | 'TEXT_TO_MUSIC'
  | 'AUDIO_TRANSCRIPTION';

export interface ModelCapabilityDefinition {
  id: string;
  name: string;
  provider: string; // 'gemini' | 'openai' | 'groq' | 'deepseek' | 'xai' | 'huggingface' | 'ollama' | 'flux' | 'stability'
  providerName: string;
  category: 'chat' | 'image' | 'video' | 'audio';
  taskTypes: TaskType[];
  inputModalities: Modality[];
  outputModalities: Modality[];
  supportsText: boolean;
  supportsVision: boolean;
  supportsImageGeneration: boolean;
  supportsImageEditing: boolean;
  supportsTextToImage: boolean;
  supportsImageToImage: boolean;
  supportsTextToVideo: boolean;
  supportsImageToVideo: boolean;
  supportsVideoEditing: boolean;
  supportsSearch: boolean;
  supportsStreaming: boolean;
  supportsTools: boolean;
  contextWindow?: number;
  pricingClass: 'FREE_ALLOWANCE' | 'PAID_API' | 'LOCAL' | 'SELF_HOSTED';
  latencyClass: 'ULTRA_FAST' | 'FAST' | 'BALANCED' | 'THOROUGH';
  qualityClass: 'DRAFT' | 'STANDARD' | 'HIGH' | 'MAXIMUM';
  isConfigured: () => boolean;
}

export const KNOWN_MODELS: ModelCapabilityDefinition[] = [
  // ========================================================
  // 0. FAL.AI HIGH-SPEED MODELS
  // ========================================================
  {
    id: 'fal-ai/flux/schnell',
    name: 'FLUX.1 Schnell',
    provider: 'fal',
    providerName: 'Fal.ai',
    category: 'image',
    taskTypes: ['TEXT_TO_IMAGE', 'IMAGE_TO_IMAGE'],
    inputModalities: ['text', 'image'],
    outputModalities: ['image'],
    supportsText: false,
    supportsVision: true,
    supportsImageGeneration: true,
    supportsImageEditing: true,
    supportsTextToImage: true,
    supportsImageToImage: true,
    supportsTextToVideo: false,
    supportsImageToVideo: false,
    supportsVideoEditing: false,
    supportsSearch: false,
    supportsStreaming: false,
    supportsTools: false,
    pricingClass: 'PAID_API',
    latencyClass: 'FAST',
    qualityClass: 'MAXIMUM',
    isConfigured: () => !!process.env.FAL_KEY,
  },

  // ========================================================
  // 1. GEMINI MODELS
  // ========================================================
  {
    id: 'gemini-3.8-flash',
    name: 'Gemini 3.8 Flash',
    provider: 'gemini',
    providerName: 'Google Gemini',
    category: 'chat',
    taskTypes: ['CHAT', 'CODING', 'VISION_ANALYSIS', 'REASONING'],
    inputModalities: ['text', 'image', 'audio', 'video'],
    outputModalities: ['text'],
    supportsText: true,
    supportsVision: true,
    supportsImageGeneration: false,
    supportsImageEditing: false,
    supportsTextToImage: false,
    supportsImageToImage: false,
    supportsTextToVideo: false,
    supportsImageToVideo: false,
    supportsVideoEditing: false,
    supportsSearch: true,
    supportsStreaming: true,
    supportsTools: true,
    contextWindow: 1048576,
    pricingClass: 'FREE_ALLOWANCE',
    latencyClass: 'FAST',
    qualityClass: 'HIGH',
    isConfigured: () => !!process.env.GEMINI_API_KEY,
  },
  {
    id: 'gemini-3.5-flash',
    name: 'Gemini 3.5 Flash (Grounded Search)',
    provider: 'gemini',
    providerName: 'Google Gemini',
    category: 'chat',
    taskTypes: ['CHAT', 'RESEARCH', 'VISION_ANALYSIS'],
    inputModalities: ['text', 'image'],
    outputModalities: ['text'],
    supportsText: true,
    supportsVision: true,
    supportsImageGeneration: false,
    supportsImageEditing: false,
    supportsTextToImage: false,
    supportsImageToImage: false,
    supportsTextToVideo: false,
    supportsImageToVideo: false,
    supportsVideoEditing: false,
    supportsSearch: true,
    supportsStreaming: true,
    supportsTools: true,
    contextWindow: 1048576,
    pricingClass: 'FREE_ALLOWANCE',
    latencyClass: 'FAST',
    qualityClass: 'HIGH',
    isConfigured: () => !!process.env.GEMINI_API_KEY,
  },
  {
    id: 'gemini-3.1-flash-image-preview',
    name: 'Gemini 3.1 Flash Image',
    provider: 'gemini',
    providerName: 'Google Cloud (GenAI)',
    category: 'image',
    taskTypes: ['TEXT_TO_IMAGE', 'IMAGE_TO_IMAGE'],
    inputModalities: ['text', 'image'],
    outputModalities: ['image'],
    supportsText: false,
    supportsVision: true,
    supportsImageGeneration: true,
    supportsImageEditing: true,
    supportsTextToImage: true,
    supportsImageToImage: true,
    supportsTextToVideo: false,
    supportsImageToVideo: false,
    supportsVideoEditing: false,
    supportsSearch: false,
    supportsStreaming: false,
    supportsTools: false,
    pricingClass: 'PAID_API',
    latencyClass: 'FAST',
    qualityClass: 'HIGH',
    isConfigured: () => !!process.env.GEMINI_API_KEY,
  },
  {
    id: 'veo-3.1-fast-generate-preview',
    name: 'Google Veo 3.1 Video Generator',
    provider: 'gemini',
    providerName: 'Google Cloud (Veo Video)',
    category: 'video',
    taskTypes: ['TEXT_TO_VIDEO', 'IMAGE_TO_VIDEO'],
    inputModalities: ['text', 'image'],
    outputModalities: ['video'],
    supportsText: false,
    supportsVision: true,
    supportsImageGeneration: false,
    supportsImageEditing: false,
    supportsTextToImage: false,
    supportsImageToImage: false,
    supportsTextToVideo: true,
    supportsImageToVideo: true,
    supportsVideoEditing: false,
    supportsSearch: false,
    supportsStreaming: false,
    supportsTools: false,
    pricingClass: 'PAID_API',
    latencyClass: 'THOROUGH',
    qualityClass: 'MAXIMUM',
    isConfigured: () => !!process.env.GEMINI_API_KEY,
  },

  // ========================================================
  // 2. OPENAI MODELS
  // ========================================================
  {
    id: 'gpt-4o-mini',
    name: 'OpenAI GPT-4o Mini',
    provider: 'openai',
    providerName: 'OpenAI',
    category: 'chat',
    taskTypes: ['CHAT', 'CODING', 'VISION_ANALYSIS', 'REASONING'],
    inputModalities: ['text', 'image'],
    outputModalities: ['text'],
    supportsText: true,
    supportsVision: true,
    supportsImageGeneration: false,
    supportsImageEditing: false,
    supportsTextToImage: false,
    supportsImageToImage: false,
    supportsTextToVideo: false,
    supportsImageToVideo: false,
    supportsVideoEditing: false,
    supportsSearch: false,
    supportsStreaming: true,
    supportsTools: true,
    contextWindow: 128000,
    pricingClass: 'PAID_API',
    latencyClass: 'FAST',
    qualityClass: 'HIGH',
    isConfigured: () => !!process.env.OPENAI_API_KEY,
  },
  {
    id: 'gpt-4o',
    name: 'OpenAI GPT-4o',
    provider: 'openai',
    providerName: 'OpenAI',
    category: 'chat',
    taskTypes: ['CHAT', 'CODING', 'VISION_ANALYSIS', 'REASONING'],
    inputModalities: ['text', 'image'],
    outputModalities: ['text'],
    supportsText: true,
    supportsVision: true,
    supportsImageGeneration: false,
    supportsImageEditing: false,
    supportsTextToImage: false,
    supportsImageToImage: false,
    supportsTextToVideo: false,
    supportsImageToVideo: false,
    supportsVideoEditing: false,
    supportsSearch: false,
    supportsStreaming: true,
    supportsTools: true,
    contextWindow: 128000,
    pricingClass: 'PAID_API',
    latencyClass: 'BALANCED',
    qualityClass: 'MAXIMUM',
    isConfigured: () => !!process.env.OPENAI_API_KEY,
  },
  {
    id: 'dall-e-3',
    name: 'OpenAI DALL·E 3 (GPT Image)',
    provider: 'openai',
    providerName: 'OpenAI (GPT Image)',
    category: 'image',
    taskTypes: ['TEXT_TO_IMAGE'],
    inputModalities: ['text'],
    outputModalities: ['image'],
    supportsText: false,
    supportsVision: false,
    supportsImageGeneration: true,
    supportsImageEditing: false,
    supportsTextToImage: true,
    supportsImageToImage: false,
    supportsTextToVideo: false,
    supportsImageToVideo: false,
    supportsVideoEditing: false,
    supportsSearch: false,
    supportsStreaming: false,
    supportsTools: false,
    pricingClass: 'PAID_API',
    latencyClass: 'BALANCED',
    qualityClass: 'HIGH',
    isConfigured: () => !!process.env.OPENAI_API_KEY,
  },

  // ========================================================
  // 3. XAI / GROK MODELS
  // ========================================================
  {
    id: 'grok-beta',
    name: 'xAI Grok Chat',
    provider: 'xai',
    providerName: 'xAI Grok',
    category: 'chat',
    taskTypes: ['CHAT', 'CODING', 'REASONING'],
    inputModalities: ['text'],
    outputModalities: ['text'],
    supportsText: true,
    supportsVision: false,
    supportsImageGeneration: false,
    supportsImageEditing: false,
    supportsTextToImage: false,
    supportsImageToImage: false,
    supportsTextToVideo: false,
    supportsImageToVideo: false,
    supportsVideoEditing: false,
    supportsSearch: true,
    supportsStreaming: true,
    supportsTools: true,
    contextWindow: 131072,
    pricingClass: 'PAID_API',
    latencyClass: 'FAST',
    qualityClass: 'HIGH',
    isConfigured: () => !!process.env.XAI_API_KEY,
  },
  {
    id: 'grok-imagine-image-2.0',
    name: 'xAI Grok Imagine Image 2.0',
    provider: 'xai',
    providerName: 'xAI Grok Imagine',
    category: 'image',
    taskTypes: ['TEXT_TO_IMAGE', 'IMAGE_TO_IMAGE'],
    inputModalities: ['text', 'image'],
    outputModalities: ['image'],
    supportsText: false,
    supportsVision: true,
    supportsImageGeneration: true,
    supportsImageEditing: true,
    supportsTextToImage: true,
    supportsImageToImage: true,
    supportsTextToVideo: false,
    supportsImageToVideo: false,
    supportsVideoEditing: false,
    supportsSearch: false,
    supportsStreaming: false,
    supportsTools: false,
    pricingClass: 'PAID_API',
    latencyClass: 'FAST',
    qualityClass: 'HIGH',
    isConfigured: () => !!process.env.XAI_API_KEY,
  },
  {
    id: 'grok-imagine-video-1.5',
    name: 'xAI Grok Imagine Video 1.5',
    provider: 'xai',
    providerName: 'xAI Grok Video',
    category: 'video',
    taskTypes: ['TEXT_TO_VIDEO', 'IMAGE_TO_VIDEO'],
    inputModalities: ['text', 'image'],
    outputModalities: ['video'],
    supportsText: false,
    supportsVision: true,
    supportsImageGeneration: false,
    supportsImageEditing: false,
    supportsTextToImage: false,
    supportsImageToImage: false,
    supportsTextToVideo: true,
    supportsImageToVideo: true,
    supportsVideoEditing: false,
    supportsSearch: false,
    supportsStreaming: false,
    supportsTools: false,
    pricingClass: 'PAID_API',
    latencyClass: 'THOROUGH',
    qualityClass: 'HIGH',
    isConfigured: () => !!process.env.XAI_API_KEY,
  },

  // ========================================================
  // 4. GROQ LPU (Strictly Text & VLM - NO Image/Video Generation)
  // ========================================================
  {
    id: 'llama-3.3-70b-versatile',
    name: 'Groq Llama 3.3 70B',
    provider: 'groq',
    providerName: 'Groq LPU Engine',
    category: 'chat',
    taskTypes: ['CHAT', 'CODING', 'REASONING'],
    inputModalities: ['text'],
    outputModalities: ['text'],
    supportsText: true,
    supportsVision: false,
    supportsImageGeneration: false,
    supportsImageEditing: false,
    supportsTextToImage: false,
    supportsImageToImage: false,
    supportsTextToVideo: false,
    supportsImageToVideo: false,
    supportsVideoEditing: false,
    supportsSearch: false,
    supportsStreaming: true,
    supportsTools: true,
    contextWindow: 128000,
    pricingClass: 'FREE_ALLOWANCE',
    latencyClass: 'ULTRA_FAST',
    qualityClass: 'HIGH',
    isConfigured: () => !!process.env.GROQ_API_KEY,
  },

  // ========================================================
  // 5. DEEPSEEK (Strictly Reasoning & Coding - NO Image/Video Generation)
  // ========================================================
  {
    id: 'deepseek-chat',
    name: 'DeepSeek-V3',
    provider: 'deepseek',
    providerName: 'DeepSeek AI',
    category: 'chat',
    taskTypes: ['CHAT', 'CODING'],
    inputModalities: ['text'],
    outputModalities: ['text'],
    supportsText: true,
    supportsVision: false,
    supportsImageGeneration: false,
    supportsImageEditing: false,
    supportsTextToImage: false,
    supportsImageToImage: false,
    supportsTextToVideo: false,
    supportsImageToVideo: false,
    supportsVideoEditing: false,
    supportsSearch: false,
    supportsStreaming: true,
    supportsTools: true,
    contextWindow: 65536,
    pricingClass: 'PAID_API',
    latencyClass: 'FAST',
    qualityClass: 'HIGH',
    isConfigured: () => !!process.env.DEEPSEEK_API_KEY,
  },
  {
    id: 'deepseek-reasoner',
    name: 'DeepSeek-R1 (Chain-of-Thought)',
    provider: 'deepseek',
    providerName: 'DeepSeek AI',
    category: 'chat',
    taskTypes: ['REASONING', 'CODING'],
    inputModalities: ['text'],
    outputModalities: ['text'],
    supportsText: true,
    supportsVision: false,
    supportsImageGeneration: false,
    supportsImageEditing: false,
    supportsTextToImage: false,
    supportsImageToImage: false,
    supportsTextToVideo: false,
    supportsImageToVideo: false,
    supportsVideoEditing: false,
    supportsSearch: false,
    supportsStreaming: true,
    supportsTools: false,
    contextWindow: 65536,
    pricingClass: 'PAID_API',
    latencyClass: 'THOROUGH',
    qualityClass: 'MAXIMUM',
    isConfigured: () => !!process.env.DEEPSEEK_API_KEY,
  },

  // ========================================================
  // 6. HUGGING FACE INFERENCE (Dynamic Image/Video/Chat)
  // ========================================================
  {
    id: 'hf-black-forest-labs/FLUX.1-schnell',
    name: 'Hugging Face FLUX.1 [schnell]',
    provider: 'huggingface',
    providerName: 'Hugging Face Inference',
    category: 'image',
    taskTypes: ['TEXT_TO_IMAGE'],
    inputModalities: ['text'],
    outputModalities: ['image'],
    supportsText: false,
    supportsVision: false,
    supportsImageGeneration: true,
    supportsImageEditing: false,
    supportsTextToImage: true,
    supportsImageToImage: false,
    supportsTextToVideo: false,
    supportsImageToVideo: false,
    supportsVideoEditing: false,
    supportsSearch: false,
    supportsStreaming: false,
    supportsTools: false,
    pricingClass: 'FREE_ALLOWANCE',
    latencyClass: 'FAST',
    qualityClass: 'HIGH',
    isConfigured: () => !!process.env.HF_TOKEN,
  },

  // ========================================================
  // 7. LOCAL FLUX & STABLE DIFFUSION
  // ========================================================
  {
    id: 'flux-1-schnell',
    name: 'FLUX.1 [schnell]',
    provider: 'flux',
    providerName: 'Black Forest Labs (Self-Hosted)',
    category: 'image',
    taskTypes: ['TEXT_TO_IMAGE', 'IMAGE_TO_IMAGE'],
    inputModalities: ['text', 'image'],
    outputModalities: ['image'],
    supportsText: false,
    supportsVision: true,
    supportsImageGeneration: true,
    supportsImageEditing: true,
    supportsTextToImage: true,
    supportsImageToImage: true,
    supportsTextToVideo: false,
    supportsImageToVideo: false,
    supportsVideoEditing: false,
    supportsSearch: false,
    supportsStreaming: false,
    supportsTools: false,
    pricingClass: 'SELF_HOSTED',
    latencyClass: 'FAST',
    qualityClass: 'HIGH',
    isConfigured: () => !!process.env.FLUX_API_URL && process.env.FLUX_ENABLED === 'true',
  },
  {
    id: 'sdxl-1.0',
    name: 'Stable Diffusion XL',
    provider: 'stability',
    providerName: 'Stability AI / Local SD',
    category: 'image',
    taskTypes: ['TEXT_TO_IMAGE', 'IMAGE_TO_IMAGE'],
    inputModalities: ['text', 'image'],
    outputModalities: ['image'],
    supportsText: false,
    supportsVision: true,
    supportsImageGeneration: true,
    supportsImageEditing: true,
    supportsTextToImage: true,
    supportsImageToImage: true,
    supportsTextToVideo: false,
    supportsImageToVideo: false,
    supportsVideoEditing: false,
    supportsSearch: false,
    supportsStreaming: false,
    supportsTools: false,
    pricingClass: 'SELF_HOSTED',
    latencyClass: 'BALANCED',
    qualityClass: 'STANDARD',
    isConfigured: () => !!process.env.SD_API_URL && process.env.SD_ENABLED === 'true',
  },
];
